services:

  transaction-service:
    build:
      context: ./transaction-service
    container_name: transaction-service

    ports:
      - "8080:8080"

    environment:
      SPRING_PROFILES_ACTIVE: benchmark

    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus

    ports:
      - "9090:9090"

    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana

    ports:
      - "3000:3000"

    depends_on:
      - prometheus