spring.application.name=accounting

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.password=${ORACLE_PASSWORD:Ict$db19}
spring.datasource.url=${ORACLE_URL:jdbc:oracle:thin:@172.16.11.7:1521:kermanora12c}
spring.datasource.username=${ORACLE_USERNAME:MHESAM}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true